// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlfwzudharffupfllhga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsZnd6dWRoYXJmZnVwZmxsaGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDM0NDAsImV4cCI6MjA2NTY3OTQ0MH0.rVYhGQr-Iy_IdmggXF6ibXCJbu1EBF0v4mLXw5Wrg00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);